apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-name: docker-agent-pod
spec:
  containers:
    - name: docker
      image: docker:latest
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
      command:
        - cat
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
