apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-name: do-k8-agent-pod
spec:
  containers:
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      envFrom:
        - configMapRef:
            name: cd-config
        - secretRef:
            name: cd-secrets
