apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-name: do-k8-agent-pod
spec:
  containers:
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_BUILDKIT
          value: 1
        - name: DOCKER_CLI_EXPERIMENTAL
          value: "enabled"
    - name: helm
      image: thepro/doctl-helm-kubectl
      envFrom:
        - secretRef:
            name: cd-secrets
      command:
        - cat
      tty: true
